import {useEffect, useState} from 'react';
import weatherApi from '../api/weatherApi';

export const useForecastResponse = (location) => {
  const [isLoading, setIsLoading] = useState(true);
  const [forecastResponse, setForecastResponse] = useState([]);
  const getForecastResponse = async () => {
    try {
      const response = await weatherApi.get(
        `/forecast.json?&q=${location}&days=2&aqi=no&alerts=no`,
      );
      setForecastResponse(response.data);
        setIsLoading(false);
     
    } catch (error) {
        console.log(error);
    }
  };

  useEffect(() => {
    getForecastResponse();
  }, []);

  return {isLoading, forecastResponse};
};




const resp = {
    "location": {
        "name": "Chillan",
        "region": "Bio-Bio",
        "country": "Chile",
        "lat": -36.6,
        "lon": -72.12,
        "tz_id": "America/Santiago",
        "localtime_epoch": 1657760449,
        "localtime": "2022-07-13 21:00"
    },
    "current": {
        "last_updated_epoch": 1657756800,
        "last_updated": "2022-07-13 20:00",
        "temp_c": 3.0,
        "temp_f": 37.4,
        "is_day": 0,
        "condition": {
            "text": "Moderate rain",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
            "code": 1189
        },
        "wind_mph": 5.6,
        "wind_kph": 9.0,
        "wind_degree": 270,
        "wind_dir": "W",
        "pressure_mb": 1012.0,
        "pressure_in": 29.88,
        "precip_mm": 24.7,
        "precip_in": 0.97,
        "humidity": 100,
        "cloud": 100,
        "feelslike_c": 2.1,
        "feelslike_f": 35.8,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 1.0,
        "gust_mph": 4.3,
        "gust_kph": 6.8
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2022-07-13",
                "date_epoch": 1657670400,
                "day": {
                    "maxtemp_c": 6.8,
                    "maxtemp_f": 44.2,
                    "mintemp_c": 0.3,
                    "mintemp_f": 32.5,
                    "avgtemp_c": 4.8,
                    "avgtemp_f": 40.6,
                    "maxwind_mph": 9.8,
                    "maxwind_kph": 15.8,
                    "totalprecip_mm": 99.0,
                    "totalprecip_in": 3.9,
                    "avgvis_km": 5.6,
                    "avgvis_miles": 3.0,
                    "avghumidity": 96.0,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 99,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 5,
                    "condition": {
                        "text": "Heavy rain",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/308.png",
                        "code": 1195
                    },
                    "uv": 1.0
                },
                "astro": {
                    "sunrise": "07:58 AM",
                    "sunset": "05:50 PM",
                    "moonrise": "05:42 PM",
                    "moonset": "08:06 AM",
                    "moon_phase": "Waxing Gibbous",
                    "moon_illumination": "99"
                },
                "hour": [
                    {
                        "time_epoch": 1657684800,
                        "time": "2022-07-13 00:00",
                        "temp_c": 6.7,
                        "temp_f": 44.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 9.4,
                        "wind_kph": 15.1,
                        "wind_degree": 31,
                        "wind_dir": "NNE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.4,
                        "precip_in": 0.02,
                        "humidity": 90,
                        "cloud": 100,
                        "feelslike_c": 3.8,
                        "feelslike_f": 38.8,
                        "windchill_c": 3.8,
                        "windchill_f": 38.8,
                        "heatindex_c": 6.7,
                        "heatindex_f": 44.1,
                        "dewpoint_c": 5.2,
                        "dewpoint_f": 41.4,
                        "will_it_rain": 1,
                        "chance_of_rain": 99,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 15.9,
                        "gust_kph": 25.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657688400,
                        "time": "2022-07-13 01:00",
                        "temp_c": 6.8,
                        "temp_f": 44.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 7.4,
                        "wind_kph": 11.9,
                        "wind_degree": 15,
                        "wind_dir": "NNE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 29.99,
                        "precip_mm": 0.5,
                        "precip_in": 0.02,
                        "humidity": 92,
                        "cloud": 100,
                        "feelslike_c": 4.5,
                        "feelslike_f": 40.1,
                        "windchill_c": 4.5,
                        "windchill_f": 40.1,
                        "heatindex_c": 6.8,
                        "heatindex_f": 44.2,
                        "dewpoint_c": 5.6,
                        "dewpoint_f": 42.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 98,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 12.1,
                        "gust_kph": 19.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657692000,
                        "time": "2022-07-13 02:00",
                        "temp_c": 6.6,
                        "temp_f": 43.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Moderate rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
                            "code": 1189
                        },
                        "wind_mph": 6.0,
                        "wind_kph": 9.7,
                        "wind_degree": 17,
                        "wind_dir": "NNE",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.98,
                        "precip_mm": 3.0,
                        "precip_in": 0.12,
                        "humidity": 93,
                        "cloud": 100,
                        "feelslike_c": 4.6,
                        "feelslike_f": 40.3,
                        "windchill_c": 4.6,
                        "windchill_f": 40.3,
                        "heatindex_c": 6.6,
                        "heatindex_f": 43.9,
                        "dewpoint_c": 5.5,
                        "dewpoint_f": 41.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 98,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 7.0,
                        "vis_miles": 4.0,
                        "gust_mph": 10.1,
                        "gust_kph": 16.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657695600,
                        "time": "2022-07-13 03:00",
                        "temp_c": 6.4,
                        "temp_f": 43.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 5.1,
                        "wind_kph": 8.3,
                        "wind_degree": 31,
                        "wind_dir": "NNE",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.97,
                        "precip_mm": 0.4,
                        "precip_in": 0.02,
                        "humidity": 94,
                        "cloud": 100,
                        "feelslike_c": 4.7,
                        "feelslike_f": 40.5,
                        "windchill_c": 4.7,
                        "windchill_f": 40.5,
                        "heatindex_c": 6.4,
                        "heatindex_f": 43.5,
                        "dewpoint_c": 5.5,
                        "dewpoint_f": 41.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 98,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 8.5,
                        "gust_kph": 13.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657699200,
                        "time": "2022-07-13 04:00",
                        "temp_c": 6.6,
                        "temp_f": 43.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 4.0,
                        "wind_kph": 6.5,
                        "wind_degree": 26,
                        "wind_dir": "NNE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.95,
                        "precip_mm": 0.2,
                        "precip_in": 0.01,
                        "humidity": 94,
                        "cloud": 100,
                        "feelslike_c": 5.4,
                        "feelslike_f": 41.7,
                        "windchill_c": 5.4,
                        "windchill_f": 41.7,
                        "heatindex_c": 6.6,
                        "heatindex_f": 43.9,
                        "dewpoint_c": 5.7,
                        "dewpoint_f": 42.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 97,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 6.5,
                        "gust_kph": 10.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657702800,
                        "time": "2022-07-13 05:00",
                        "temp_c": 6.7,
                        "temp_f": 44.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 1.8,
                        "wind_kph": 2.9,
                        "wind_degree": 44,
                        "wind_dir": "NE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.94,
                        "precip_mm": 0.6,
                        "precip_in": 0.02,
                        "humidity": 95,
                        "cloud": 100,
                        "feelslike_c": 6.7,
                        "feelslike_f": 44.1,
                        "windchill_c": 6.7,
                        "windchill_f": 44.1,
                        "heatindex_c": 6.7,
                        "heatindex_f": 44.1,
                        "dewpoint_c": 6.0,
                        "dewpoint_f": 42.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 63,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 2.9,
                        "gust_kph": 4.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657706400,
                        "time": "2022-07-13 06:00",
                        "temp_c": 6.8,
                        "temp_f": 44.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 0.9,
                        "wind_kph": 1.4,
                        "wind_degree": 177,
                        "wind_dir": "S",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.3,
                        "precip_in": 0.01,
                        "humidity": 96,
                        "cloud": 100,
                        "feelslike_c": 6.8,
                        "feelslike_f": 44.2,
                        "windchill_c": 6.8,
                        "windchill_f": 44.2,
                        "heatindex_c": 6.8,
                        "heatindex_f": 44.2,
                        "dewpoint_c": 6.3,
                        "dewpoint_f": 43.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 99,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 1.3,
                        "gust_kph": 2.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657710000,
                        "time": "2022-07-13 07:00",
                        "temp_c": 6.8,
                        "temp_f": 44.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 121,
                        "wind_dir": "ESE",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.92,
                        "precip_mm": 0.5,
                        "precip_in": 0.02,
                        "humidity": 97,
                        "cloud": 100,
                        "feelslike_c": 6.1,
                        "feelslike_f": 43.0,
                        "windchill_c": 6.1,
                        "windchill_f": 43.0,
                        "heatindex_c": 6.8,
                        "heatindex_f": 44.2,
                        "dewpoint_c": 6.4,
                        "dewpoint_f": 43.5,
                        "will_it_rain": 1,
                        "chance_of_rain": 98,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 4.9,
                        "gust_kph": 7.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657713600,
                        "time": "2022-07-13 08:00",
                        "temp_c": 6.8,
                        "temp_f": 44.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Moderate rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                            "code": 1189
                        },
                        "wind_mph": 4.3,
                        "wind_kph": 6.8,
                        "wind_degree": 201,
                        "wind_dir": "SSW",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 4.1,
                        "precip_in": 0.16,
                        "humidity": 98,
                        "cloud": 100,
                        "feelslike_c": 5.5,
                        "feelslike_f": 41.9,
                        "windchill_c": 5.5,
                        "windchill_f": 41.9,
                        "heatindex_c": 6.8,
                        "heatindex_f": 44.2,
                        "dewpoint_c": 6.5,
                        "dewpoint_f": 43.7,
                        "will_it_rain": 1,
                        "chance_of_rain": 98,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 7.0,
                        "vis_miles": 4.0,
                        "gust_mph": 6.5,
                        "gust_kph": 10.4,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1657717200,
                        "time": "2022-07-13 09:00",
                        "temp_c": 6.8,
                        "temp_f": 44.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 6.5,
                        "wind_kph": 10.4,
                        "wind_degree": 177,
                        "wind_dir": "S",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.91,
                        "precip_mm": 0.9,
                        "precip_in": 0.04,
                        "humidity": 96,
                        "cloud": 100,
                        "feelslike_c": 4.7,
                        "feelslike_f": 40.5,
                        "windchill_c": 4.7,
                        "windchill_f": 40.5,
                        "heatindex_c": 6.8,
                        "heatindex_f": 44.2,
                        "dewpoint_c": 6.2,
                        "dewpoint_f": 43.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 98,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 9.6,
                        "gust_kph": 15.5,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1657720800,
                        "time": "2022-07-13 10:00",
                        "temp_c": 6.3,
                        "temp_f": 43.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 9.8,
                        "wind_kph": 15.8,
                        "wind_degree": 198,
                        "wind_dir": "SSW",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.92,
                        "precip_mm": 1.5,
                        "precip_in": 0.06,
                        "humidity": 95,
                        "cloud": 100,
                        "feelslike_c": 3.2,
                        "feelslike_f": 37.8,
                        "windchill_c": 3.2,
                        "windchill_f": 37.8,
                        "heatindex_c": 6.3,
                        "heatindex_f": 43.3,
                        "dewpoint_c": 5.5,
                        "dewpoint_f": 41.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 97,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 13.6,
                        "gust_kph": 22.0,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1657724400,
                        "time": "2022-07-13 11:00",
                        "temp_c": 6.1,
                        "temp_f": 43.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Moderate rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                            "code": 1189
                        },
                        "wind_mph": 8.9,
                        "wind_kph": 14.4,
                        "wind_degree": 188,
                        "wind_dir": "S",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.92,
                        "precip_mm": 4.1,
                        "precip_in": 0.16,
                        "humidity": 95,
                        "cloud": 100,
                        "feelslike_c": 3.2,
                        "feelslike_f": 37.8,
                        "windchill_c": 3.2,
                        "windchill_f": 37.8,
                        "heatindex_c": 6.1,
                        "heatindex_f": 43.0,
                        "dewpoint_c": 5.3,
                        "dewpoint_f": 41.5,
                        "will_it_rain": 1,
                        "chance_of_rain": 99,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 7.0,
                        "vis_miles": 4.0,
                        "gust_mph": 12.1,
                        "gust_kph": 19.4,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1657728000,
                        "time": "2022-07-13 12:00",
                        "temp_c": 5.8,
                        "temp_f": 42.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 6.7,
                        "wind_kph": 10.8,
                        "wind_degree": 203,
                        "wind_dir": "SSW",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.91,
                        "precip_mm": 1.4,
                        "precip_in": 0.06,
                        "humidity": 96,
                        "cloud": 100,
                        "feelslike_c": 3.5,
                        "feelslike_f": 38.3,
                        "windchill_c": 3.5,
                        "windchill_f": 38.3,
                        "heatindex_c": 5.8,
                        "heatindex_f": 42.4,
                        "dewpoint_c": 5.2,
                        "dewpoint_f": 41.4,
                        "will_it_rain": 1,
                        "chance_of_rain": 99,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 9.2,
                        "gust_kph": 14.8,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1657731600,
                        "time": "2022-07-13 13:00",
                        "temp_c": 5.6,
                        "temp_f": 42.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 6.9,
                        "wind_kph": 11.2,
                        "wind_degree": 189,
                        "wind_dir": "S",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 1.3,
                        "precip_in": 0.05,
                        "humidity": 95,
                        "cloud": 100,
                        "feelslike_c": 3.1,
                        "feelslike_f": 37.6,
                        "windchill_c": 3.1,
                        "windchill_f": 37.6,
                        "heatindex_c": 5.6,
                        "heatindex_f": 42.1,
                        "dewpoint_c": 4.8,
                        "dewpoint_f": 40.6,
                        "will_it_rain": 1,
                        "chance_of_rain": 98,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 9.2,
                        "gust_kph": 14.8,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1657735200,
                        "time": "2022-07-13 14:00",
                        "temp_c": 5.3,
                        "temp_f": 41.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Heavy rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/308.png",
                            "code": 1195
                        },
                        "wind_mph": 7.6,
                        "wind_kph": 12.2,
                        "wind_degree": 209,
                        "wind_dir": "SSW",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.87,
                        "precip_mm": 7.8,
                        "precip_in": 0.31,
                        "humidity": 96,
                        "cloud": 100,
                        "feelslike_c": 2.6,
                        "feelslike_f": 36.7,
                        "windchill_c": 2.6,
                        "windchill_f": 36.7,
                        "heatindex_c": 5.3,
                        "heatindex_f": 41.5,
                        "dewpoint_c": 4.7,
                        "dewpoint_f": 40.5,
                        "will_it_rain": 1,
                        "chance_of_rain": 98,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 5.0,
                        "vis_miles": 3.0,
                        "gust_mph": 9.8,
                        "gust_kph": 15.8,
                        "uv": 2.0
                    },
                    {
                        "time_epoch": 1657738800,
                        "time": "2022-07-13 15:00",
                        "temp_c": 4.9,
                        "temp_f": 40.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Moderate rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                            "code": 1189
                        },
                        "wind_mph": 8.5,
                        "wind_kph": 13.7,
                        "wind_degree": 212,
                        "wind_dir": "SSW",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.87,
                        "precip_mm": 2.8,
                        "precip_in": 0.11,
                        "humidity": 97,
                        "cloud": 100,
                        "feelslike_c": 1.8,
                        "feelslike_f": 35.2,
                        "windchill_c": 1.8,
                        "windchill_f": 35.2,
                        "heatindex_c": 4.9,
                        "heatindex_f": 40.8,
                        "dewpoint_c": 4.4,
                        "dewpoint_f": 39.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 98,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 7.0,
                        "vis_miles": 4.0,
                        "gust_mph": 11.0,
                        "gust_kph": 17.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657742400,
                        "time": "2022-07-13 16:00",
                        "temp_c": 4.6,
                        "temp_f": 40.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Moderate rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                            "code": 1189
                        },
                        "wind_mph": 8.5,
                        "wind_kph": 13.7,
                        "wind_degree": 208,
                        "wind_dir": "SSW",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 2.9,
                        "precip_in": 0.11,
                        "humidity": 97,
                        "cloud": 100,
                        "feelslike_c": 1.5,
                        "feelslike_f": 34.7,
                        "windchill_c": 1.5,
                        "windchill_f": 34.7,
                        "heatindex_c": 4.6,
                        "heatindex_f": 40.3,
                        "dewpoint_c": 4.1,
                        "dewpoint_f": 39.4,
                        "will_it_rain": 1,
                        "chance_of_rain": 97,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 7.0,
                        "vis_miles": 4.0,
                        "gust_mph": 10.7,
                        "gust_kph": 17.3,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657746000,
                        "time": "2022-07-13 17:00",
                        "temp_c": 3.1,
                        "temp_f": 37.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Heavy rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/308.png",
                            "code": 1195
                        },
                        "wind_mph": 7.2,
                        "wind_kph": 11.5,
                        "wind_degree": 193,
                        "wind_dir": "SSW",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 10.1,
                        "precip_in": 0.4,
                        "humidity": 98,
                        "cloud": 100,
                        "feelslike_c": 0.0,
                        "feelslike_f": 32.0,
                        "windchill_c": 0.0,
                        "windchill_f": 32.0,
                        "heatindex_c": 3.1,
                        "heatindex_f": 37.6,
                        "dewpoint_c": 2.9,
                        "dewpoint_f": 37.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 97,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 5.0,
                        "vis_miles": 3.0,
                        "gust_mph": 9.4,
                        "gust_kph": 15.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657749600,
                        "time": "2022-07-13 18:00",
                        "temp_c": 1.8,
                        "temp_f": 35.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Moderate rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
                            "code": 1189
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 199,
                        "wind_dir": "SSW",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.89,
                        "precip_mm": 3.9,
                        "precip_in": 0.15,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -1.2,
                        "feelslike_f": 29.8,
                        "windchill_c": -1.2,
                        "windchill_f": 29.8,
                        "heatindex_c": 1.8,
                        "heatindex_f": 35.2,
                        "dewpoint_c": 1.8,
                        "dewpoint_f": 35.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 97,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 7.0,
                        "vis_miles": 4.0,
                        "gust_mph": 8.7,
                        "gust_kph": 14.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657753200,
                        "time": "2022-07-13 19:00",
                        "temp_c": 1.4,
                        "temp_f": 34.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Moderate rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
                            "code": 1189
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 193,
                        "wind_dir": "SSW",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.9,
                        "precip_mm": 4.1,
                        "precip_in": 0.16,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": 0.0,
                        "feelslike_f": 32.0,
                        "windchill_c": 0.0,
                        "windchill_f": 32.0,
                        "heatindex_c": 1.4,
                        "heatindex_f": 34.5,
                        "dewpoint_c": 1.3,
                        "dewpoint_f": 34.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 96,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 7.0,
                        "vis_miles": 4.0,
                        "gust_mph": 4.7,
                        "gust_kph": 7.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657756800,
                        "time": "2022-07-13 20:00",
                        "temp_c": 1.2,
                        "temp_f": 34.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Heavy rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/308.png",
                            "code": 1195
                        },
                        "wind_mph": 2.7,
                        "wind_kph": 4.3,
                        "wind_degree": 183,
                        "wind_dir": "S",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.91,
                        "precip_mm": 24.7,
                        "precip_in": 0.97,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": 0.1,
                        "feelslike_f": 32.2,
                        "windchill_c": 0.1,
                        "windchill_f": 32.2,
                        "heatindex_c": 1.2,
                        "heatindex_f": 34.2,
                        "dewpoint_c": 1.2,
                        "dewpoint_f": 34.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 96,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 5.0,
                        "vis_miles": 3.0,
                        "gust_mph": 4.3,
                        "gust_kph": 6.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657760400,
                        "time": "2022-07-13 21:00",
                        "temp_c": 1.2,
                        "temp_f": 34.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Moderate rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
                            "code": 1189
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 221,
                        "wind_dir": "SW",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.9,
                        "precip_mm": 5.1,
                        "precip_in": 0.2,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -0.4,
                        "feelslike_f": 31.3,
                        "windchill_c": -0.4,
                        "windchill_f": 31.3,
                        "heatindex_c": 1.2,
                        "heatindex_f": 34.2,
                        "dewpoint_c": 1.2,
                        "dewpoint_f": 34.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 96,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 7.0,
                        "vis_miles": 4.0,
                        "gust_mph": 5.4,
                        "gust_kph": 8.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657764000,
                        "time": "2022-07-13 22:00",
                        "temp_c": 0.5,
                        "temp_f": 32.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Moderate rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
                            "code": 1189
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 237,
                        "wind_dir": "WSW",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.9,
                        "precip_mm": 4.8,
                        "precip_in": 0.19,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -2.0,
                        "feelslike_f": 28.4,
                        "windchill_c": -2.0,
                        "windchill_f": 28.4,
                        "heatindex_c": 0.5,
                        "heatindex_f": 32.9,
                        "dewpoint_c": 0.5,
                        "dewpoint_f": 32.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 60,
                        "vis_km": 7.0,
                        "vis_miles": 4.0,
                        "gust_mph": 7.8,
                        "gust_kph": 12.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657767600,
                        "time": "2022-07-13 23:00",
                        "temp_c": 0.3,
                        "temp_f": 32.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Moderate or heavy sleet",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/320.png",
                            "code": 1207
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 259,
                        "wind_dir": "W",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.9,
                        "precip_mm": 13.6,
                        "precip_in": 0.54,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -1.7,
                        "feelslike_f": 28.9,
                        "windchill_c": -1.7,
                        "windchill_f": 28.9,
                        "heatindex_c": 0.3,
                        "heatindex_f": 32.5,
                        "dewpoint_c": 0.3,
                        "dewpoint_f": 32.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 61,
                        "vis_km": 6.0,
                        "vis_miles": 3.0,
                        "gust_mph": 6.3,
                        "gust_kph": 10.1,
                        "uv": 1.0
                    }
                ]
            },
            {
                "date": "2022-07-14",
                "date_epoch": 1657756800,
                "day": {
                    "maxtemp_c": 4.7,
                    "maxtemp_f": 40.5,
                    "mintemp_c": 0.1,
                    "mintemp_f": 32.2,
                    "avgtemp_c": 2.0,
                    "avgtemp_f": 35.6,
                    "maxwind_mph": 7.4,
                    "maxwind_kph": 11.9,
                    "totalprecip_mm": 53.0,
                    "totalprecip_in": 2.09,
                    "avgvis_km": 4.3,
                    "avgvis_miles": 2.0,
                    "avghumidity": 100.0,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 89,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 27,
                    "condition": {
                        "text": "Heavy rain",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/308.png",
                        "code": 1195
                    },
                    "uv": 1.0
                },
                "astro": {
                    "sunrise": "07:58 AM",
                    "sunset": "05:51 PM",
                    "moonrise": "06:58 PM",
                    "moonset": "09:02 AM",
                    "moon_phase": "Full Moon",
                    "moon_illumination": "100"
                },
                "hour": [
                    {
                        "time_epoch": 1657771200,
                        "time": "2022-07-14 00:00",
                        "temp_c": 0.1,
                        "temp_f": 32.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Moderate or heavy sleet",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/320.png",
                            "code": 1207
                        },
                        "wind_mph": 2.0,
                        "wind_kph": 3.2,
                        "wind_degree": 260,
                        "wind_dir": "W",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.91,
                        "precip_mm": 4.3,
                        "precip_in": 0.17,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -0.5,
                        "feelslike_f": 31.1,
                        "windchill_c": -0.5,
                        "windchill_f": 31.1,
                        "heatindex_c": 0.1,
                        "heatindex_f": 32.2,
                        "dewpoint_c": 0.1,
                        "dewpoint_f": 32.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 64,
                        "vis_km": 6.0,
                        "vis_miles": 3.0,
                        "gust_mph": 3.4,
                        "gust_kph": 5.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657774800,
                        "time": "2022-07-14 01:00",
                        "temp_c": 0.1,
                        "temp_f": 32.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Moderate or heavy sleet",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/320.png",
                            "code": 1207
                        },
                        "wind_mph": 1.8,
                        "wind_kph": 2.9,
                        "wind_degree": 239,
                        "wind_dir": "WSW",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.9,
                        "precip_mm": 3.8,
                        "precip_in": 0.15,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": 0.1,
                        "feelslike_f": 32.2,
                        "windchill_c": 0.1,
                        "windchill_f": 32.2,
                        "heatindex_c": 0.1,
                        "heatindex_f": 32.2,
                        "dewpoint_c": 0.1,
                        "dewpoint_f": 32.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 1,
                        "chance_of_snow": 71,
                        "vis_km": 6.0,
                        "vis_miles": 3.0,
                        "gust_mph": 2.9,
                        "gust_kph": 4.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657778400,
                        "time": "2022-07-14 02:00",
                        "temp_c": 0.2,
                        "temp_f": 32.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Moderate or heavy sleet",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/320.png",
                            "code": 1207
                        },
                        "wind_mph": 0.9,
                        "wind_kph": 1.4,
                        "wind_degree": 290,
                        "wind_dir": "WNW",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.89,
                        "precip_mm": 20.3,
                        "precip_in": 0.8,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": 0.2,
                        "feelslike_f": 32.4,
                        "windchill_c": 0.2,
                        "windchill_f": 32.4,
                        "heatindex_c": 0.2,
                        "heatindex_f": 32.4,
                        "dewpoint_c": 0.2,
                        "dewpoint_f": 32.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 60,
                        "vis_km": 6.0,
                        "vis_miles": 3.0,
                        "gust_mph": 1.6,
                        "gust_kph": 2.5,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657782000,
                        "time": "2022-07-14 03:00",
                        "temp_c": 0.3,
                        "temp_f": 32.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Light sleet",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/317.png",
                            "code": 1204
                        },
                        "wind_mph": 2.2,
                        "wind_kph": 3.6,
                        "wind_degree": 300,
                        "wind_dir": "WNW",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.91,
                        "precip_mm": 0.2,
                        "precip_in": 0.01,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -0.5,
                        "feelslike_f": 31.1,
                        "windchill_c": -0.5,
                        "windchill_f": 31.1,
                        "heatindex_c": 0.3,
                        "heatindex_f": 32.5,
                        "dewpoint_c": 0.3,
                        "dewpoint_f": 32.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 1,
                        "chance_of_snow": 86,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 3.6,
                        "gust_kph": 5.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657785600,
                        "time": "2022-07-14 04:00",
                        "temp_c": 0.4,
                        "temp_f": 32.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                            "code": 1135
                        },
                        "wind_mph": 2.9,
                        "wind_kph": 4.7,
                        "wind_degree": 2,
                        "wind_dir": "N",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.92,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -1.0,
                        "feelslike_f": 30.2,
                        "windchill_c": -1.0,
                        "windchill_f": 30.2,
                        "heatindex_c": 0.4,
                        "heatindex_f": 32.7,
                        "dewpoint_c": 0.4,
                        "dewpoint_f": 32.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 65,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 4.7,
                        "gust_kph": 7.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657789200,
                        "time": "2022-07-14 05:00",
                        "temp_c": 0.5,
                        "temp_f": 32.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Light sleet",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/317.png",
                            "code": 1204
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 51,
                        "wind_dir": "NE",
                        "pressure_mb": 1013.0,
                        "pressure_in": 29.92,
                        "precip_mm": 0.4,
                        "precip_in": 0.02,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -1.5,
                        "feelslike_f": 29.3,
                        "windchill_c": -1.5,
                        "windchill_f": 29.3,
                        "heatindex_c": 0.5,
                        "heatindex_f": 32.9,
                        "dewpoint_c": 0.5,
                        "dewpoint_f": 32.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 1,
                        "chance_of_snow": 88,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 6.3,
                        "gust_kph": 10.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657792800,
                        "time": "2022-07-14 06:00",
                        "temp_c": 0.8,
                        "temp_f": 33.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                            "code": 1135
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 48,
                        "wind_dir": "NE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.93,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -1.8,
                        "feelslike_f": 28.8,
                        "windchill_c": -1.8,
                        "windchill_f": 28.8,
                        "heatindex_c": 0.8,
                        "heatindex_f": 33.4,
                        "dewpoint_c": 0.8,
                        "dewpoint_f": 33.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 1,
                        "chance_of_snow": 86,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 7.8,
                        "gust_kph": 12.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657796400,
                        "time": "2022-07-14 07:00",
                        "temp_c": 0.8,
                        "temp_f": 33.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                            "code": 1135
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 44,
                        "wind_dir": "NE",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.96,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -2.0,
                        "feelslike_f": 28.4,
                        "windchill_c": -2.0,
                        "windchill_f": 28.4,
                        "heatindex_c": 0.8,
                        "heatindex_f": 33.4,
                        "dewpoint_c": 0.8,
                        "dewpoint_f": 33.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 1,
                        "chance_of_snow": 73,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 8.7,
                        "gust_kph": 14.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657800000,
                        "time": "2022-07-14 08:00",
                        "temp_c": 0.9,
                        "temp_f": 33.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Light sleet",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/317.png",
                            "code": 1204
                        },
                        "wind_mph": 7.2,
                        "wind_kph": 11.5,
                        "wind_degree": 37,
                        "wind_dir": "NE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 29.99,
                        "precip_mm": 0.4,
                        "precip_in": 0.02,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -2.6,
                        "feelslike_f": 27.3,
                        "windchill_c": -2.6,
                        "windchill_f": 27.3,
                        "heatindex_c": 0.9,
                        "heatindex_f": 33.6,
                        "dewpoint_c": 0.9,
                        "dewpoint_f": 33.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 60,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 11.6,
                        "gust_kph": 18.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657803600,
                        "time": "2022-07-14 09:00",
                        "temp_c": 1.1,
                        "temp_f": 34.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                            "code": 1135
                        },
                        "wind_mph": 7.4,
                        "wind_kph": 11.9,
                        "wind_degree": 35,
                        "wind_dir": "NE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -2.4,
                        "feelslike_f": 27.7,
                        "windchill_c": -2.4,
                        "windchill_f": 27.7,
                        "heatindex_c": 1.1,
                        "heatindex_f": 34.0,
                        "dewpoint_c": 1.1,
                        "dewpoint_f": 34.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 11.9,
                        "gust_kph": 19.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657807200,
                        "time": "2022-07-14 10:00",
                        "temp_c": 1.5,
                        "temp_f": 34.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                            "code": 1135
                        },
                        "wind_mph": 6.5,
                        "wind_kph": 10.4,
                        "wind_degree": 39,
                        "wind_dir": "NE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.01,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -1.6,
                        "feelslike_f": 29.1,
                        "windchill_c": -1.6,
                        "windchill_f": 29.1,
                        "heatindex_c": 1.5,
                        "heatindex_f": 34.7,
                        "dewpoint_c": 1.5,
                        "dewpoint_f": 34.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 10.3,
                        "gust_kph": 16.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657810800,
                        "time": "2022-07-14 11:00",
                        "temp_c": 2.2,
                        "temp_f": 36.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                            "code": 1135
                        },
                        "wind_mph": 6.0,
                        "wind_kph": 9.7,
                        "wind_degree": 50,
                        "wind_dir": "NE",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.02,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -0.6,
                        "feelslike_f": 30.9,
                        "windchill_c": -0.6,
                        "windchill_f": 30.9,
                        "heatindex_c": 2.2,
                        "heatindex_f": 36.0,
                        "dewpoint_c": 2.2,
                        "dewpoint_f": 36.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 9.4,
                        "gust_kph": 15.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657814400,
                        "time": "2022-07-14 12:00",
                        "temp_c": 2.8,
                        "temp_f": 37.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                            "code": 1135
                        },
                        "wind_mph": 5.6,
                        "wind_kph": 9.0,
                        "wind_degree": 20,
                        "wind_dir": "NNE",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.02,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": 0.3,
                        "feelslike_f": 32.5,
                        "windchill_c": 0.3,
                        "windchill_f": 32.5,
                        "heatindex_c": 2.8,
                        "heatindex_f": 37.0,
                        "dewpoint_c": 2.7,
                        "dewpoint_f": 36.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 8.5,
                        "gust_kph": 13.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657818000,
                        "time": "2022-07-14 13:00",
                        "temp_c": 3.3,
                        "temp_f": 37.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                            "code": 1135
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 35,
                        "wind_dir": "NE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.0,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 99,
                        "cloud": 100,
                        "feelslike_c": 0.6,
                        "feelslike_f": 33.1,
                        "windchill_c": 0.6,
                        "windchill_f": 33.1,
                        "heatindex_c": 3.3,
                        "heatindex_f": 37.9,
                        "dewpoint_c": 3.2,
                        "dewpoint_f": 37.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 9.2,
                        "gust_kph": 14.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657821600,
                        "time": "2022-07-14 14:00",
                        "temp_c": 3.9,
                        "temp_f": 39.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                            "code": 1135
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 18,
                        "wind_dir": "NNE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 29.99,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 99,
                        "cloud": 100,
                        "feelslike_c": 2.4,
                        "feelslike_f": 36.3,
                        "windchill_c": 2.4,
                        "windchill_f": 36.3,
                        "heatindex_c": 3.9,
                        "heatindex_f": 39.0,
                        "dewpoint_c": 3.8,
                        "dewpoint_f": 38.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 5.6,
                        "gust_kph": 9.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657825200,
                        "time": "2022-07-14 15:00",
                        "temp_c": 4.5,
                        "temp_f": 40.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                            "code": 1135
                        },
                        "wind_mph": 1.6,
                        "wind_kph": 2.5,
                        "wind_degree": 44,
                        "wind_dir": "NE",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.98,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 99,
                        "cloud": 100,
                        "feelslike_c": 4.5,
                        "feelslike_f": 40.1,
                        "windchill_c": 4.5,
                        "windchill_f": 40.1,
                        "heatindex_c": 4.5,
                        "heatindex_f": 40.1,
                        "dewpoint_c": 4.4,
                        "dewpoint_f": 39.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 2.2,
                        "gust_kph": 3.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657828800,
                        "time": "2022-07-14 16:00",
                        "temp_c": 4.7,
                        "temp_f": 40.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Fog",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                            "code": 1135
                        },
                        "wind_mph": 2.0,
                        "wind_kph": 3.2,
                        "wind_degree": 208,
                        "wind_dir": "SSW",
                        "pressure_mb": 1015.0,
                        "pressure_in": 29.97,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 99,
                        "cloud": 100,
                        "feelslike_c": 4.6,
                        "feelslike_f": 40.3,
                        "windchill_c": 4.6,
                        "windchill_f": 40.3,
                        "heatindex_c": 4.7,
                        "heatindex_f": 40.5,
                        "dewpoint_c": 4.6,
                        "dewpoint_f": 40.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 0.0,
                        "vis_miles": 0.0,
                        "gust_mph": 2.9,
                        "gust_kph": 4.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657832400,
                        "time": "2022-07-14 17:00",
                        "temp_c": 3.5,
                        "temp_f": 38.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 6.7,
                        "wind_kph": 10.8,
                        "wind_degree": 213,
                        "wind_dir": "SSW",
                        "pressure_mb": 1014.0,
                        "pressure_in": 29.96,
                        "precip_mm": 1.0,
                        "precip_in": 0.04,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": 0.7,
                        "feelslike_f": 33.3,
                        "windchill_c": 0.7,
                        "windchill_f": 33.3,
                        "heatindex_c": 3.5,
                        "heatindex_f": 38.3,
                        "dewpoint_c": 3.5,
                        "dewpoint_f": 38.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 89,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 11.2,
                        "gust_kph": 18.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657836000,
                        "time": "2022-07-14 18:00",
                        "temp_c": 2.2,
                        "temp_f": 36.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                            "code": 1183
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 281,
                        "wind_dir": "WNW",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.0,
                        "precip_mm": 1.6,
                        "precip_in": 0.06,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": -0.3,
                        "feelslike_f": 31.5,
                        "windchill_c": -0.3,
                        "windchill_f": 31.5,
                        "heatindex_c": 2.2,
                        "heatindex_f": 36.0,
                        "dewpoint_c": 2.2,
                        "dewpoint_f": 36.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 88,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 8.3,
                        "gust_kph": 13.3,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657839600,
                        "time": "2022-07-14 19:00",
                        "temp_c": 1.7,
                        "temp_f": 35.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                            "code": 1183
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 154,
                        "wind_dir": "SSE",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.02,
                        "precip_mm": 1.8,
                        "precip_in": 0.07,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": 0.2,
                        "feelslike_f": 32.4,
                        "windchill_c": 0.2,
                        "windchill_f": 32.4,
                        "heatindex_c": 1.7,
                        "heatindex_f": 35.1,
                        "dewpoint_c": 1.7,
                        "dewpoint_f": 35.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 88,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 5.6,
                        "gust_kph": 9.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657843200,
                        "time": "2022-07-14 20:00",
                        "temp_c": 2.2,
                        "temp_f": 36.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Heavy rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/308.png",
                            "code": 1195
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 80,
                        "wind_dir": "E",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.04,
                        "precip_mm": 10.7,
                        "precip_in": 0.42,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": 0.0,
                        "feelslike_f": 32.0,
                        "windchill_c": 0.0,
                        "windchill_f": 32.0,
                        "heatindex_c": 2.2,
                        "heatindex_f": 36.0,
                        "dewpoint_c": 2.2,
                        "dewpoint_f": 36.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 85,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 5.0,
                        "vis_miles": 3.0,
                        "gust_mph": 8.5,
                        "gust_kph": 13.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657846800,
                        "time": "2022-07-14 21:00",
                        "temp_c": 2.9,
                        "temp_f": 37.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                            "code": 1183
                        },
                        "wind_mph": 4.0,
                        "wind_kph": 6.5,
                        "wind_degree": 65,
                        "wind_dir": "ENE",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.04,
                        "precip_mm": 2.3,
                        "precip_in": 0.09,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": 1.1,
                        "feelslike_f": 34.0,
                        "windchill_c": 1.1,
                        "windchill_f": 34.0,
                        "heatindex_c": 2.9,
                        "heatindex_f": 37.2,
                        "dewpoint_c": 2.9,
                        "dewpoint_f": 37.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 87,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 7.4,
                        "gust_kph": 11.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657850400,
                        "time": "2022-07-14 22:00",
                        "temp_c": 3.3,
                        "temp_f": 37.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                            "code": 1183
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 102,
                        "wind_dir": "ESE",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.04,
                        "precip_mm": 1.9,
                        "precip_in": 0.07,
                        "humidity": 100,
                        "cloud": 100,
                        "feelslike_c": 0.8,
                        "feelslike_f": 33.4,
                        "windchill_c": 0.8,
                        "windchill_f": 33.4,
                        "heatindex_c": 3.3,
                        "heatindex_f": 37.9,
                        "dewpoint_c": 3.2,
                        "dewpoint_f": 37.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 74,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 11.2,
                        "gust_kph": 18.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1657854000,
                        "time": "2022-07-14 23:00",
                        "temp_c": 3.7,
                        "temp_f": 38.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Moderate rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
                            "code": 1189
                        },
                        "wind_mph": 5.6,
                        "wind_kph": 9.0,
                        "wind_degree": 94,
                        "wind_dir": "E",
                        "pressure_mb": 1017.0,
                        "pressure_in": 30.03,
                        "precip_mm": 4.0,
                        "precip_in": 0.16,
                        "humidity": 98,
                        "cloud": 100,
                        "feelslike_c": 1.3,
                        "feelslike_f": 34.3,
                        "windchill_c": 1.3,
                        "windchill_f": 34.3,
                        "heatindex_c": 3.7,
                        "heatindex_f": 38.7,
                        "dewpoint_c": 3.5,
                        "dewpoint_f": 38.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 89,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 7.0,
                        "vis_miles": 4.0,
                        "gust_mph": 11.4,
                        "gust_kph": 18.4,
                        "uv": 1.0
                    }
                ]
            }
        ]
    }
}
